### ISSUE TITLE
Right click

### ISSUE THREAD

**Issue by OleePizza** [Ma0us/pizza#1]
Please make a right click feature, so you can right click where you type the text and be able to fast paste.
I don't use it because I use CTRL + V but its something that should be added.

**Comment by OleePizza** [comment]
![Screenshot 2022-05-07 233721](https://user-images.githubusercontent.com/93055297/167272419-11dd962f-8d17-4b31-91ed-83fd13551e07.png)
for me this is hard to read and hurting my eyes and when I zoom in its looking to fancy.
I am using **BOLD** and Calibri as my font.
Is this possible to fix?

**Comment by Ma0us** [comment]
working on fixing fonts so you can change it to whatever font you prefer
